apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: route-1390
spec:
  source:
    properties:
      period: 15000
      message: "{\"message\": \"Hello from Camel\", \"name\": \"Phil P\" }"
      contentType: application/json
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: timer-source
    types: {}
  steps:
  - properties: {}
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: log-action
    types: {}
  sink:
    properties:
      type: phil.camel.test
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: philsbroker
    types: {}
