apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: sendfromcamel
spec:
  source:
    properties:
      message: "{\"message\": \"Hello\", \"name\": \"Phil P\" }"
      contentType: application/json
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: timer-source
    types: {}
  sink:
    properties:
      type: phil.camel.test
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: philsbroker
    types: {}
